server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/consumerdb
    username: root
    password: processor1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  topic: order-topic

spring.kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: order-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: '*'